# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\开发启蒙\可用工具开发\EnableTools\BondPledge.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EnableTool(object):
    def setupUi(self, EnableTool):
        EnableTool.setObjectName("EnableTool")
        EnableTool.resize(1200, 618)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/En/En.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EnableTool.setWindowIcon(icon)
        EnableTool.setStyleSheet("")
        EnableTool.setTabShape(QtWidgets.QTabWidget.Triangular)
        EnableTool.setDockNestingEnabled(False)
        EnableTool.setUnifiedTitleAndToolBarOnMac(False)
        self.centralWidget = QtWidgets.QWidget(EnableTool)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 195))
        self.groupBox.setMaximumSize(QtCore.QSize(259, 197))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 231, 159))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.c_entrust_status = QtWidgets.QComboBox(self.layoutWidget)
        self.c_entrust_status.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.c_entrust_status.setFont(font)
        self.c_entrust_status.setFrame(True)
        self.c_entrust_status.setObjectName("c_entrust_status")
        self.c_entrust_status.addItem("")
        self.gridLayout_3.addWidget(self.c_entrust_status, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 2, 0, 1, 1)
        self.c_entrust_price = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.c_entrust_price.setFont(font)
        self.c_entrust_price.setMaximum(1.0)
        self.c_entrust_price.setSingleStep(0.01)
        self.c_entrust_price.setProperty("value", 0.98)
        self.c_entrust_price.setObjectName("c_entrust_price")
        self.gridLayout_3.addWidget(self.c_entrust_price, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.c_entrust_direction = QtWidgets.QComboBox(self.layoutWidget)
        self.c_entrust_direction.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.c_entrust_direction.setFont(font)
        self.c_entrust_direction.setObjectName("c_entrust_direction")
        self.c_entrust_direction.addItem("")
        self.c_entrust_direction.addItem("")
        self.gridLayout_3.addWidget(self.c_entrust_direction, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 3, 0, 1, 1)
        self.c_entrust_amount = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c_entrust_amount.sizePolicy().hasHeightForWidth())
        self.c_entrust_amount.setSizePolicy(sizePolicy)
        self.c_entrust_amount.setMinimumSize(QtCore.QSize(0, 0))
        self.c_entrust_amount.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.c_entrust_amount.setFont(font)
        self.c_entrust_amount.setAccelerated(False)
        self.c_entrust_amount.setMinimum(100)
        self.c_entrust_amount.setMaximum(1000000)
        self.c_entrust_amount.setSingleStep(100)
        self.c_entrust_amount.setProperty("value", 100)
        self.c_entrust_amount.setDisplayIntegerBase(10)
        self.c_entrust_amount.setObjectName("c_entrust_amount")
        self.gridLayout_3.addWidget(self.c_entrust_amount, 3, 1, 1, 1)
        self.c_stock_type = QtWidgets.QComboBox(self.layoutWidget)
        self.c_stock_type.setEnabled(False)
        self.c_stock_type.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.c_stock_type.setFont(font)
        self.c_stock_type.setStyleSheet("")
        self.c_stock_type.setObjectName("c_stock_type")
        self.c_stock_type.addItem("")
        self.gridLayout_3.addWidget(self.c_stock_type, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 4, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(259, 196))
        self.groupBox_2.setMaximumSize(QtCore.QSize(259, 196))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnExport = QtWidgets.QPushButton(self.groupBox_2)
        self.btnExport.setMaximumSize(QtCore.QSize(107, 16777215))
        self.btnExport.setObjectName("btnExport")
        self.gridLayout_4.addWidget(self.btnExport, 1, 1, 1, 1)
        self.btnCalculate = QtWidgets.QPushButton(self.groupBox_2)
        self.btnCalculate.setMaximumSize(QtCore.QSize(107, 16777215))
        self.btnCalculate.setObjectName("btnCalculate")
        self.gridLayout_4.addWidget(self.btnCalculate, 0, 0, 1, 1)
        self.btnInit = QtWidgets.QPushButton(self.groupBox_2)
        self.btnInit.setMaximumSize(QtCore.QSize(107, 16777215))
        self.btnInit.setObjectName("btnInit")
        self.gridLayout_4.addWidget(self.btnInit, 1, 0, 1, 1)
        self.btnClear = QtWidgets.QPushButton(self.groupBox_2)
        self.btnClear.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnClear.setObjectName("btnClear")
        self.gridLayout_4.addWidget(self.btnClear, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 109, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tableWidgetCurrent = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidgetCurrent.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetCurrent.sizePolicy().hasHeightForWidth())
        self.tableWidgetCurrent.setSizePolicy(sizePolicy)
        self.tableWidgetCurrent.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidgetCurrent.setMaximumSize(QtCore.QSize(16777215, 123))
        self.tableWidgetCurrent.setStyleSheet("")
        self.tableWidgetCurrent.setLineWidth(1)
        self.tableWidgetCurrent.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidgetCurrent.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidgetCurrent.setAutoScroll(True)
        self.tableWidgetCurrent.setAutoScrollMargin(20)
        self.tableWidgetCurrent.setDragEnabled(True)
        self.tableWidgetCurrent.setShowGrid(True)
        self.tableWidgetCurrent.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetCurrent.setWordWrap(False)
        self.tableWidgetCurrent.setObjectName("tableWidgetCurrent")
        self.tableWidgetCurrent.setColumnCount(14)
        self.tableWidgetCurrent.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(0, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(2, 0, item)
        self.tableWidgetCurrent.horizontalHeader().setVisible(True)
        self.tableWidgetCurrent.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetCurrent.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidgetCurrent.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidgetCurrent.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetCurrent.verticalHeader().setVisible(False)
        self.tableWidgetCurrent.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidgetCurrent.verticalHeader().setDefaultSectionSize(26)
        self.tableWidgetCurrent.verticalHeader().setHighlightSections(True)
        self.tableWidgetCurrent.verticalHeader().setMinimumSectionSize(21)
        self.tableWidgetCurrent.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.tableWidgetCurrent)
        spacerItem2 = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.tableWidgetStock = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidgetStock.setMinimumSize(QtCore.QSize(0, 123))
        self.tableWidgetStock.setMaximumSize(QtCore.QSize(16777215, 123))
        self.tableWidgetStock.setStyleSheet("")
        self.tableWidgetStock.setCornerButtonEnabled(True)
        self.tableWidgetStock.setObjectName("tableWidgetStock")
        self.tableWidgetStock.setColumnCount(13)
        self.tableWidgetStock.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(2, 0, item)
        self.tableWidgetStock.verticalHeader().setVisible(False)
        self.tableWidgetStock.verticalHeader().setDefaultSectionSize(26)
        self.tableWidgetStock.verticalHeader().setHighlightSections(True)
        self.tableWidgetStock.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.tableWidgetStock)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        EnableTool.setCentralWidget(self.centralWidget)

        self.retranslateUi(EnableTool)
        QtCore.QMetaObject.connectSlotsByName(EnableTool)

    def retranslateUi(self, EnableTool):
        _translate = QtCore.QCoreApplication.translate
        EnableTool.setWindowTitle(_translate("EnableTool", "债券质押"))
        self.groupBox.setTitle(_translate("EnableTool", "输入参数"))
        self.c_entrust_status.setItemText(0, _translate("EnableTool", "已成"))
        self.label_12.setText(_translate("EnableTool", "委托状态："))
        self.label_10.setText(_translate("EnableTool", "业务品种："))
        self.c_entrust_direction.setItemText(0, _translate("EnableTool", "提交质押"))
        self.c_entrust_direction.setItemText(1, _translate("EnableTool", "转回质押"))
        self.label_13.setText(_translate("EnableTool", "委托数量："))
        self.c_stock_type.setItemText(0, _translate("EnableTool", "债券"))
        self.label_15.setText(_translate("EnableTool", "委托方向："))
        self.label_14.setText(_translate("EnableTool", "质押比例："))
        self.groupBox_2.setTitle(_translate("EnableTool", "功能函数"))
        self.btnExport.setText(_translate("EnableTool", "导出"))
        self.btnCalculate.setText(_translate("EnableTool", "计算"))
        self.btnInit.setText(_translate("EnableTool", "系统初始化"))
        self.btnClear.setText(_translate("EnableTool", "清空"))
        self.tableWidgetCurrent.setSortingEnabled(False)
        item = self.tableWidgetCurrent.verticalHeaderItem(0)
        item.setText(_translate("EnableTool", "初始状态"))
        item = self.tableWidgetCurrent.verticalHeaderItem(1)
        item.setText(_translate("EnableTool", "计算后状态"))
        item = self.tableWidgetCurrent.verticalHeaderItem(2)
        item.setText(_translate("EnableTool", "系统初始化后状态"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(0)
        item.setText(_translate("EnableTool", "持仓变化"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(1)
        item.setText(_translate("EnableTool", "业务品种"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(2)
        item.setText(_translate("EnableTool", "委托方向"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(3)
        item.setText(_translate("EnableTool", "委托数量"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(4)
        item.setText(_translate("EnableTool", "质押比例"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(5)
        item.setText(_translate("EnableTool", "委托状态"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(6)
        item.setText(_translate("EnableTool", "当前持仓数量"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(7)
        item.setText(_translate("EnableTool", "可用数量"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(8)
        item.setText(_translate("EnableTool", "冻结数量"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(9)
        item.setText(_translate("EnableTool", "解冻数量"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(10)
        item.setText(_translate("EnableTool", "质押数量"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(11)
        item.setText(_translate("EnableTool", "成本价"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(12)
        item.setText(_translate("EnableTool", "成本"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(13)
        item.setText(_translate("EnableTool", "含费用成本"))
        __sortingEnabled = self.tableWidgetCurrent.isSortingEnabled()
        self.tableWidgetCurrent.setSortingEnabled(False)
        item = self.tableWidgetCurrent.item(0, 0)
        item.setText(_translate("EnableTool", "初始状态"))
        item = self.tableWidgetCurrent.item(0, 6)
        item.setText(_translate("EnableTool", "10000"))
        item = self.tableWidgetCurrent.item(0, 7)
        item.setText(_translate("EnableTool", "10000"))
        item = self.tableWidgetCurrent.item(0, 8)
        item.setText(_translate("EnableTool", "500"))
        item = self.tableWidgetCurrent.item(0, 9)
        item.setText(_translate("EnableTool", "0"))
        item = self.tableWidgetCurrent.item(0, 10)
        item.setText(_translate("EnableTool", "500"))
        item = self.tableWidgetCurrent.item(0, 11)
        item.setText(_translate("EnableTool", "100"))
        item = self.tableWidgetCurrent.item(0, 12)
        item.setText(_translate("EnableTool", "1000000"))
        item = self.tableWidgetCurrent.item(0, 13)
        item.setText(_translate("EnableTool", "1000000"))
        item = self.tableWidgetCurrent.item(1, 0)
        item.setText(_translate("EnableTool", "计算后状态"))
        item = self.tableWidgetCurrent.item(2, 0)
        item.setText(_translate("EnableTool", "初始化后状态"))
        self.tableWidgetCurrent.setSortingEnabled(__sortingEnabled)
        self.tableWidgetStock.setSortingEnabled(True)
        item = self.tableWidgetStock.verticalHeaderItem(0)
        item.setText(_translate("EnableTool", "初始状态"))
        item = self.tableWidgetStock.verticalHeaderItem(1)
        item.setText(_translate("EnableTool", "计算后状态"))
        item = self.tableWidgetStock.verticalHeaderItem(2)
        item.setText(_translate("EnableTool", "系统初始化后状态"))
        item = self.tableWidgetStock.horizontalHeaderItem(0)
        item.setText(_translate("EnableTool", "标准券变化"))
        item = self.tableWidgetStock.horizontalHeaderItem(1)
        item.setText(_translate("EnableTool", "业务品种"))
        item = self.tableWidgetStock.horizontalHeaderItem(2)
        item.setText(_translate("EnableTool", "委托方向"))
        item = self.tableWidgetStock.horizontalHeaderItem(3)
        item.setText(_translate("EnableTool", "委托数量"))
        item = self.tableWidgetStock.horizontalHeaderItem(4)
        item.setText(_translate("EnableTool", "质押比例"))
        item = self.tableWidgetStock.horizontalHeaderItem(5)
        item.setText(_translate("EnableTool", "委托状态"))
        item = self.tableWidgetStock.horizontalHeaderItem(6)
        item.setText(_translate("EnableTool", "当前持仓数量"))
        item = self.tableWidgetStock.horizontalHeaderItem(7)
        item.setText(_translate("EnableTool", "可用数量"))
        item = self.tableWidgetStock.horizontalHeaderItem(8)
        item.setText(_translate("EnableTool", "冻结数量"))
        item = self.tableWidgetStock.horizontalHeaderItem(9)
        item.setText(_translate("EnableTool", "解冻数量"))
        item = self.tableWidgetStock.horizontalHeaderItem(10)
        item.setText(_translate("EnableTool", "成本价"))
        item = self.tableWidgetStock.horizontalHeaderItem(11)
        item.setText(_translate("EnableTool", "成本"))
        item = self.tableWidgetStock.horizontalHeaderItem(12)
        item.setText(_translate("EnableTool", "含费用成本"))
        __sortingEnabled = self.tableWidgetStock.isSortingEnabled()
        self.tableWidgetStock.setSortingEnabled(False)
        item = self.tableWidgetStock.item(0, 0)
        item.setText(_translate("EnableTool", "初始状态"))
        item = self.tableWidgetStock.item(0, 6)
        item.setText(_translate("EnableTool", "0"))
        item = self.tableWidgetStock.item(0, 7)
        item.setText(_translate("EnableTool", "10000"))
        item = self.tableWidgetStock.item(0, 8)
        item.setText(_translate("EnableTool", "0"))
        item = self.tableWidgetStock.item(0, 9)
        item.setText(_translate("EnableTool", "10000"))
        item = self.tableWidgetStock.item(0, 10)
        item.setText(_translate("EnableTool", "0"))
        item = self.tableWidgetStock.item(0, 11)
        item.setText(_translate("EnableTool", "0"))
        item = self.tableWidgetStock.item(0, 12)
        item.setText(_translate("EnableTool", "0"))
        item = self.tableWidgetStock.item(1, 0)
        item.setText(_translate("EnableTool", "计算后状态"))
        item = self.tableWidgetStock.item(2, 0)
        item.setText(_translate("EnableTool", "初始化后状态"))
        self.tableWidgetStock.setSortingEnabled(__sortingEnabled)

import ICON_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EnableTool = QtWidgets.QMainWindow()
    ui = Ui_EnableTool()
    ui.setupUi(EnableTool)
    EnableTool.show()
    sys.exit(app.exec_())

