# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\开发启蒙\可用工具开发\EnableTools\BondHG.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EnableTool(object):
    def setupUi(self, EnableTool):
        EnableTool.setObjectName("EnableTool")
        EnableTool.resize(1284, 549)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/En/En.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EnableTool.setWindowIcon(icon)
        EnableTool.setStyleSheet("")
        EnableTool.setTabShape(QtWidgets.QTabWidget.Triangular)
        EnableTool.setDockNestingEnabled(False)
        EnableTool.setUnifiedTitleAndToolBarOnMac(False)
        self.centralWidget = QtWidgets.QWidget(EnableTool)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidgetAsset = QtWidgets.QTableWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetAsset.sizePolicy().hasHeightForWidth())
        self.tableWidgetAsset.setSizePolicy(sizePolicy)
        self.tableWidgetAsset.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidgetAsset.setMaximumSize(QtCore.QSize(16777215, 145))
        self.tableWidgetAsset.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tableWidgetAsset.setToolTip("")
        self.tableWidgetAsset.setStyleSheet("")
        self.tableWidgetAsset.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidgetAsset.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidgetAsset.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidgetAsset.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetAsset.setWordWrap(True)
        self.tableWidgetAsset.setCornerButtonEnabled(True)
        self.tableWidgetAsset.setObjectName("tableWidgetAsset")
        self.tableWidgetAsset.setColumnCount(17)
        self.tableWidgetAsset.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidgetAsset.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setItem(0, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setItem(0, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setItem(0, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setItem(0, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAsset.setItem(2, 0, item)
        self.tableWidgetAsset.horizontalHeader().setVisible(True)
        self.tableWidgetAsset.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetAsset.horizontalHeader().setHighlightSections(True)
        self.tableWidgetAsset.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetAsset.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetAsset.verticalHeader().setVisible(False)
        self.tableWidgetAsset.verticalHeader().setDefaultSectionSize(23)
        self.tableWidgetAsset.verticalHeader().setHighlightSections(True)
        self.tableWidgetAsset.verticalHeader().setMinimumSectionSize(20)
        self.tableWidgetAsset.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetAsset.verticalHeader().setStretchLastSection(False)
        self.gridLayout_4.addWidget(self.tableWidgetAsset, 0, 0, 1, 4)
        self.label = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 12))
        self.label.setMaximumSize(QtCore.QSize(54, 12))
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(9, -1, 9, -1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(305, 215))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.c_stock_type = QtWidgets.QComboBox(self.groupBox)
        self.c_stock_type.setEnabled(False)
        self.c_stock_type.setMinimumSize(QtCore.QSize(126, 27))
        self.c_stock_type.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.c_stock_type.setFont(font)
        self.c_stock_type.setStyleSheet("")
        self.c_stock_type.setObjectName("c_stock_type")
        self.c_stock_type.addItem("")
        self.gridLayout.addWidget(self.c_stock_type, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 0, 1, 1)
        self.c_entrust_direction = QtWidgets.QComboBox(self.groupBox)
        self.c_entrust_direction.setMinimumSize(QtCore.QSize(0, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.c_entrust_direction.setFont(font)
        self.c_entrust_direction.setObjectName("c_entrust_direction")
        self.c_entrust_direction.addItem("")
        self.c_entrust_direction.addItem("")
        self.gridLayout.addWidget(self.c_entrust_direction, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.c_entrust_price = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.c_entrust_price.setFont(font)
        self.c_entrust_price.setSingleStep(0.01)
        self.c_entrust_price.setProperty("value", 1.0)
        self.c_entrust_price.setObjectName("c_entrust_price")
        self.gridLayout.addWidget(self.c_entrust_price, 4, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.c_entrust_amount = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.c_entrust_amount.setFont(font)
        self.c_entrust_amount.setAccelerated(False)
        self.c_entrust_amount.setMinimum(100)
        self.c_entrust_amount.setMaximum(1000000)
        self.c_entrust_amount.setSingleStep(100)
        self.c_entrust_amount.setProperty("value", 100)
        self.c_entrust_amount.setDisplayIntegerBase(10)
        self.c_entrust_amount.setObjectName("c_entrust_amount")
        self.gridLayout.addWidget(self.c_entrust_amount, 3, 1, 1, 1)
        self.c_entrust_status = QtWidgets.QComboBox(self.groupBox)
        self.c_entrust_status.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.c_entrust_status.setFont(font)
        self.c_entrust_status.setObjectName("c_entrust_status")
        self.c_entrust_status.addItem("")
        self.c_entrust_status.addItem("")
        self.gridLayout.addWidget(self.c_entrust_status, 6, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 4, 0, 1, 1)
        self.c_bond_interest = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.c_bond_interest.setFont(font)
        self.c_bond_interest.setDecimals(6)
        self.c_bond_interest.setMaximum(1.0)
        self.c_bond_interest.setSingleStep(1e-06)
        self.c_bond_interest.setProperty("value", 5.6e-05)
        self.c_bond_interest.setObjectName("c_bond_interest")
        self.gridLayout.addWidget(self.c_bond_interest, 5, 1, 1, 1)
        self.l_stock = QtWidgets.QLineEdit(self.groupBox)
        self.l_stock.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.l_stock.setFont(font)
        self.l_stock.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.l_stock.setObjectName("l_stock")
        self.gridLayout.addWidget(self.l_stock, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 4)
        self.c_bond_interest.raise_()
        self.label_15.raise_()
        self.c_entrust_amount.raise_()
        self.label_14.raise_()
        self.label_11.raise_()
        self.label_13.raise_()
        self.label_10.raise_()
        self.c_stock_type.raise_()
        self.c_entrust_direction.raise_()
        self.c_entrust_price.raise_()
        self.label_2.raise_()
        self.l_stock.raise_()
        self.c_entrust_status.raise_()
        self.label_12.raise_()
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 142))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(9, -1, 9, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnExport = QtWidgets.QPushButton(self.groupBox_2)
        self.btnExport.setMaximumSize(QtCore.QSize(107, 16777215))
        self.btnExport.setObjectName("btnExport")
        self.gridLayout_2.addWidget(self.btnExport, 2, 2, 1, 1)
        self.btnCalculate = QtWidgets.QPushButton(self.groupBox_2)
        self.btnCalculate.setMaximumSize(QtCore.QSize(107, 16777215))
        self.btnCalculate.setObjectName("btnCalculate")
        self.gridLayout_2.addWidget(self.btnCalculate, 0, 0, 1, 1)
        self.btnClear = QtWidgets.QPushButton(self.groupBox_2)
        self.btnClear.setMaximumSize(QtCore.QSize(107, 16777215))
        self.btnClear.setObjectName("btnClear")
        self.gridLayout_2.addWidget(self.btnClear, 0, 2, 1, 1)
        self.btnInit = QtWidgets.QPushButton(self.groupBox_2)
        self.btnInit.setMaximumSize(QtCore.QSize(107, 16777215))
        self.btnInit.setObjectName("btnInit")
        self.gridLayout_2.addWidget(self.btnInit, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout_4.addLayout(self.verticalLayout, 2, 0, 2, 2)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 2, 2, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidgetCurrent = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidgetCurrent.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidgetCurrent.setMaximumSize(QtCore.QSize(16777215, 123))
        self.tableWidgetCurrent.setStyleSheet("")
        self.tableWidgetCurrent.setObjectName("tableWidgetCurrent")
        self.tableWidgetCurrent.setColumnCount(14)
        self.tableWidgetCurrent.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(0, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrent.setItem(2, 0, item)
        self.tableWidgetCurrent.horizontalHeader().setVisible(True)
        self.tableWidgetCurrent.horizontalHeader().setHighlightSections(True)
        self.tableWidgetCurrent.horizontalHeader().setMinimumSectionSize(23)
        self.tableWidgetCurrent.verticalHeader().setVisible(False)
        self.tableWidgetCurrent.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidgetCurrent.verticalHeader().setDefaultSectionSize(23)
        self.tableWidgetCurrent.verticalHeader().setHighlightSections(True)
        self.tableWidgetCurrent.verticalHeader().setMinimumSectionSize(20)
        self.tableWidgetCurrent.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetCurrent.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.tableWidgetCurrent)
        spacerItem4 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.tableWidgetStock = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidgetStock.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidgetStock.setMaximumSize(QtCore.QSize(16777215, 123))
        self.tableWidgetStock.setStyleSheet("")
        self.tableWidgetStock.setCornerButtonEnabled(True)
        self.tableWidgetStock.setObjectName("tableWidgetStock")
        self.tableWidgetStock.setColumnCount(15)
        self.tableWidgetStock.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(0, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(0, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStock.setItem(2, 0, item)
        self.tableWidgetStock.verticalHeader().setVisible(False)
        self.tableWidgetStock.verticalHeader().setDefaultSectionSize(23)
        self.tableWidgetStock.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.tableWidgetStock)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem5)
        self.tableWidgetStandard = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidgetStandard.setMinimumSize(QtCore.QSize(919, 0))
        self.tableWidgetStandard.setMaximumSize(QtCore.QSize(16777215, 116))
        self.tableWidgetStandard.setStyleSheet("")
        self.tableWidgetStandard.setCornerButtonEnabled(True)
        self.tableWidgetStandard.setObjectName("tableWidgetStandard")
        self.tableWidgetStandard.setColumnCount(15)
        self.tableWidgetStandard.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setItem(0, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setItem(0, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetStandard.setItem(2, 0, item)
        self.tableWidgetStandard.verticalHeader().setVisible(False)
        self.tableWidgetStandard.verticalHeader().setDefaultSectionSize(23)
        self.tableWidgetStandard.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.tableWidgetStandard)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 2, 3, 2, 1)
        EnableTool.setCentralWidget(self.centralWidget)

        self.retranslateUi(EnableTool)
        QtCore.QMetaObject.connectSlotsByName(EnableTool)

    def retranslateUi(self, EnableTool):
        _translate = QtCore.QCoreApplication.translate
        EnableTool.setWindowTitle(_translate("EnableTool", "质押回购"))
        item = self.tableWidgetAsset.verticalHeaderItem(0)
        item.setText(_translate("EnableTool", "初始状态"))
        item = self.tableWidgetAsset.verticalHeaderItem(1)
        item.setText(_translate("EnableTool", "计算后状态"))
        item = self.tableWidgetAsset.verticalHeaderItem(2)
        item.setText(_translate("EnableTool", "系统初始化后状态"))
        item = self.tableWidgetAsset.horizontalHeaderItem(0)
        item.setText(_translate("EnableTool", "资产变化"))
        item = self.tableWidgetAsset.horizontalHeaderItem(1)
        item.setText(_translate("EnableTool", "业务品种"))
        item = self.tableWidgetAsset.horizontalHeaderItem(2)
        item.setText(_translate("EnableTool", "委托方向"))
        item = self.tableWidgetAsset.horizontalHeaderItem(3)
        item.setText(_translate("EnableTool", "证券代码"))
        item = self.tableWidgetAsset.horizontalHeaderItem(4)
        item.setText(_translate("EnableTool", "委托数量"))
        item = self.tableWidgetAsset.horizontalHeaderItem(5)
        item.setText(_translate("EnableTool", "委托价格"))
        item = self.tableWidgetAsset.horizontalHeaderItem(6)
        item.setText(_translate("EnableTool", "交易费率"))
        item = self.tableWidgetAsset.horizontalHeaderItem(7)
        item.setText(_translate("EnableTool", "委托状态"))
        item = self.tableWidgetAsset.horizontalHeaderItem(8)
        item.setText(_translate("EnableTool", "资金资产"))
        item = self.tableWidgetAsset.horizontalHeaderItem(9)
        item.setText(_translate("EnableTool", "证券资产"))
        item = self.tableWidgetAsset.horizontalHeaderItem(10)
        item.setText(_translate("EnableTool", "回购资产"))
        item = self.tableWidgetAsset.horizontalHeaderItem(11)
        item.setText(_translate("EnableTool", "应收"))
        item = self.tableWidgetAsset.horizontalHeaderItem(12)
        item.setText(_translate("EnableTool", "应付"))
        item = self.tableWidgetAsset.horizontalHeaderItem(13)
        item.setText(_translate("EnableTool", "总资产"))
        item = self.tableWidgetAsset.horizontalHeaderItem(14)
        item.setText(_translate("EnableTool", "净值"))
        item = self.tableWidgetAsset.horizontalHeaderItem(15)
        item.setText(_translate("EnableTool", "产品份额"))
        item = self.tableWidgetAsset.horizontalHeaderItem(16)
        item.setText(_translate("EnableTool", "单位净值"))
        __sortingEnabled = self.tableWidgetAsset.isSortingEnabled()
        self.tableWidgetAsset.setSortingEnabled(False)
        item = self.tableWidgetAsset.item(0, 0)
        item.setText(_translate("EnableTool", "初始状态"))
        item = self.tableWidgetAsset.item(0, 8)
        item.setText(_translate("EnableTool", "1000000.00"))
        item = self.tableWidgetAsset.item(0, 9)
        item.setText(_translate("EnableTool", "1000000.00"))
        item = self.tableWidgetAsset.item(0, 10)
        item.setText(_translate("EnableTool", "0.00"))
        item = self.tableWidgetAsset.item(0, 11)
        item.setText(_translate("EnableTool", "0.00"))
        item = self.tableWidgetAsset.item(0, 12)
        item.setText(_translate("EnableTool", "0.00"))
        item = self.tableWidgetAsset.item(0, 13)
        item.setText(_translate("EnableTool", "1000000.00"))
        item = self.tableWidgetAsset.item(0, 14)
        item.setText(_translate("EnableTool", "1000000.00"))
        item = self.tableWidgetAsset.item(0, 15)
        item.setText(_translate("EnableTool", "1000000.00"))
        item = self.tableWidgetAsset.item(0, 16)
        item.setText(_translate("EnableTool", "1.00"))
        item = self.tableWidgetAsset.item(1, 0)
        item.setText(_translate("EnableTool", "计算后状态"))
        item = self.tableWidgetAsset.item(2, 0)
        item.setText(_translate("EnableTool", "初始化后状态"))
        self.tableWidgetAsset.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("EnableTool", "输入参数"))
        self.c_stock_type.setItemText(0, _translate("EnableTool", "债券回购"))
        self.label_15.setText(_translate("EnableTool", "委托方向："))
        self.c_entrust_direction.setItemText(0, _translate("EnableTool", "融资回购"))
        self.c_entrust_direction.setItemText(1, _translate("EnableTool", "融券回购"))
        self.label_2.setText(_translate("EnableTool", "证券代码："))
        self.label_10.setText(_translate("EnableTool", "业务品种："))
        self.label_13.setText(_translate("EnableTool", "委托数量："))
        self.label_12.setText(_translate("EnableTool", "委托状态："))
        self.c_entrust_status.setItemText(0, _translate("EnableTool", "已报"))
        self.c_entrust_status.setItemText(1, _translate("EnableTool", "已成"))
        self.label_14.setText(_translate("EnableTool", "委托价格："))
        self.l_stock.setText(_translate("EnableTool", "131810"))
        self.label_11.setText(_translate("EnableTool", "交易费率："))
        self.groupBox_2.setTitle(_translate("EnableTool", "功能函数"))
        self.btnExport.setText(_translate("EnableTool", "导出"))
        self.btnCalculate.setText(_translate("EnableTool", "计算"))
        self.btnClear.setText(_translate("EnableTool", "清空"))
        self.btnInit.setText(_translate("EnableTool", "系统初始化"))
        item = self.tableWidgetCurrent.verticalHeaderItem(0)
        item.setText(_translate("EnableTool", "初始状态"))
        item = self.tableWidgetCurrent.verticalHeaderItem(1)
        item.setText(_translate("EnableTool", "计算后状态"))
        item = self.tableWidgetCurrent.verticalHeaderItem(2)
        item.setText(_translate("EnableTool", "系统初始化后状态"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(0)
        item.setText(_translate("EnableTool", "资金变化"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(1)
        item.setText(_translate("EnableTool", "业务品种"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(2)
        item.setText(_translate("EnableTool", "委托方向"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(3)
        item.setText(_translate("EnableTool", "证券代码"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(4)
        item.setText(_translate("EnableTool", "委托数量"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(5)
        item.setText(_translate("EnableTool", "委托价格"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(6)
        item.setText(_translate("EnableTool", "交易费率"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(7)
        item.setText(_translate("EnableTool", "委托状态"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(8)
        item.setText(_translate("EnableTool", "交易费"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(9)
        item.setText(_translate("EnableTool", "当前现金余额"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(10)
        item.setText(_translate("EnableTool", "T+0可用金额"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(11)
        item.setText(_translate("EnableTool", "T+1可用金额"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(12)
        item.setText(_translate("EnableTool", "冻结金额"))
        item = self.tableWidgetCurrent.horizontalHeaderItem(13)
        item.setText(_translate("EnableTool", "解冻金额"))
        __sortingEnabled = self.tableWidgetCurrent.isSortingEnabled()
        self.tableWidgetCurrent.setSortingEnabled(False)
        item = self.tableWidgetCurrent.item(0, 0)
        item.setText(_translate("EnableTool", "初始状态"))
        item = self.tableWidgetCurrent.item(0, 8)
        item.setText(_translate("EnableTool", "0"))
        item = self.tableWidgetCurrent.item(0, 9)
        item.setText(_translate("EnableTool", "1000000.00"))
        item = self.tableWidgetCurrent.item(0, 10)
        item.setText(_translate("EnableTool", "1000000.00"))
        item = self.tableWidgetCurrent.item(0, 11)
        item.setText(_translate("EnableTool", "1000000.00"))
        item = self.tableWidgetCurrent.item(0, 12)
        item.setText(_translate("EnableTool", "0.00"))
        item = self.tableWidgetCurrent.item(0, 13)
        item.setText(_translate("EnableTool", "0.00"))
        item = self.tableWidgetCurrent.item(1, 0)
        item.setText(_translate("EnableTool", "计算后状态"))
        item = self.tableWidgetCurrent.item(2, 0)
        item.setText(_translate("EnableTool", "初始化后状态"))
        self.tableWidgetCurrent.setSortingEnabled(__sortingEnabled)
        self.tableWidgetStock.setSortingEnabled(True)
        item = self.tableWidgetStock.verticalHeaderItem(0)
        item.setText(_translate("EnableTool", "初始状态"))
        item = self.tableWidgetStock.verticalHeaderItem(1)
        item.setText(_translate("EnableTool", "计算后状态"))
        item = self.tableWidgetStock.verticalHeaderItem(2)
        item.setText(_translate("EnableTool", "系统初始化后状态"))
        item = self.tableWidgetStock.horizontalHeaderItem(0)
        item.setText(_translate("EnableTool", "持仓变化"))
        item = self.tableWidgetStock.horizontalHeaderItem(1)
        item.setText(_translate("EnableTool", "业务品种"))
        item = self.tableWidgetStock.horizontalHeaderItem(2)
        item.setText(_translate("EnableTool", "委托方向"))
        item = self.tableWidgetStock.horizontalHeaderItem(3)
        item.setText(_translate("EnableTool", "证券代码"))
        item = self.tableWidgetStock.horizontalHeaderItem(4)
        item.setText(_translate("EnableTool", "委托数量"))
        item = self.tableWidgetStock.horizontalHeaderItem(5)
        item.setText(_translate("EnableTool", "委托价格"))
        item = self.tableWidgetStock.horizontalHeaderItem(6)
        item.setText(_translate("EnableTool", "交易费率"))
        item = self.tableWidgetStock.horizontalHeaderItem(7)
        item.setText(_translate("EnableTool", "委托状态"))
        item = self.tableWidgetStock.horizontalHeaderItem(8)
        item.setText(_translate("EnableTool", "当前持仓数量"))
        item = self.tableWidgetStock.horizontalHeaderItem(9)
        item.setText(_translate("EnableTool", "可用数量"))
        item = self.tableWidgetStock.horizontalHeaderItem(10)
        item.setText(_translate("EnableTool", "冻结数量"))
        item = self.tableWidgetStock.horizontalHeaderItem(11)
        item.setText(_translate("EnableTool", "解冻数量"))
        item = self.tableWidgetStock.horizontalHeaderItem(12)
        item.setText(_translate("EnableTool", "成本价"))
        item = self.tableWidgetStock.horizontalHeaderItem(13)
        item.setText(_translate("EnableTool", "成本"))
        item = self.tableWidgetStock.horizontalHeaderItem(14)
        item.setText(_translate("EnableTool", "含费用成本"))
        __sortingEnabled = self.tableWidgetStock.isSortingEnabled()
        self.tableWidgetStock.setSortingEnabled(False)
        item = self.tableWidgetStock.item(0, 0)
        item.setText(_translate("EnableTool", "初始状态"))
        item = self.tableWidgetStock.item(0, 8)
        item.setText(_translate("EnableTool", "10000"))
        item = self.tableWidgetStock.item(0, 9)
        item.setText(_translate("EnableTool", "10000"))
        item = self.tableWidgetStock.item(0, 10)
        item.setText(_translate("EnableTool", "0"))
        item = self.tableWidgetStock.item(0, 11)
        item.setText(_translate("EnableTool", "0"))
        item = self.tableWidgetStock.item(0, 12)
        item.setText(_translate("EnableTool", "100"))
        item = self.tableWidgetStock.item(0, 13)
        item.setText(_translate("EnableTool", "1000000"))
        item = self.tableWidgetStock.item(0, 14)
        item.setText(_translate("EnableTool", "1000000"))
        item = self.tableWidgetStock.item(1, 0)
        item.setText(_translate("EnableTool", "计算后状态"))
        item = self.tableWidgetStock.item(2, 0)
        item.setText(_translate("EnableTool", "初始化后状态"))
        self.tableWidgetStock.setSortingEnabled(__sortingEnabled)
        self.tableWidgetStandard.setSortingEnabled(True)
        item = self.tableWidgetStandard.verticalHeaderItem(0)
        item.setText(_translate("EnableTool", "初始状态"))
        item = self.tableWidgetStandard.verticalHeaderItem(1)
        item.setText(_translate("EnableTool", "计算后状态"))
        item = self.tableWidgetStandard.verticalHeaderItem(2)
        item.setText(_translate("EnableTool", "系统初始化后状态"))
        item = self.tableWidgetStandard.horizontalHeaderItem(0)
        item.setText(_translate("EnableTool", "标准券变化"))
        item = self.tableWidgetStandard.horizontalHeaderItem(1)
        item.setText(_translate("EnableTool", "业务品种"))
        item = self.tableWidgetStandard.horizontalHeaderItem(2)
        item.setText(_translate("EnableTool", "委托方向"))
        item = self.tableWidgetStandard.horizontalHeaderItem(3)
        item.setText(_translate("EnableTool", "证券代码"))
        item = self.tableWidgetStandard.horizontalHeaderItem(4)
        item.setText(_translate("EnableTool", "委托数量"))
        item = self.tableWidgetStandard.horizontalHeaderItem(5)
        item.setText(_translate("EnableTool", "委托价格"))
        item = self.tableWidgetStandard.horizontalHeaderItem(6)
        item.setText(_translate("EnableTool", "交易费率"))
        item = self.tableWidgetStandard.horizontalHeaderItem(7)
        item.setText(_translate("EnableTool", "委托状态"))
        item = self.tableWidgetStandard.horizontalHeaderItem(8)
        item.setText(_translate("EnableTool", "当前持仓数量"))
        item = self.tableWidgetStandard.horizontalHeaderItem(9)
        item.setText(_translate("EnableTool", "可用数量"))
        item = self.tableWidgetStandard.horizontalHeaderItem(10)
        item.setText(_translate("EnableTool", "冻结数量"))
        item = self.tableWidgetStandard.horizontalHeaderItem(11)
        item.setText(_translate("EnableTool", "解冻数量"))
        item = self.tableWidgetStandard.horizontalHeaderItem(12)
        item.setText(_translate("EnableTool", "成本价"))
        item = self.tableWidgetStandard.horizontalHeaderItem(13)
        item.setText(_translate("EnableTool", "成本"))
        item = self.tableWidgetStandard.horizontalHeaderItem(14)
        item.setText(_translate("EnableTool", "含费用成本"))
        __sortingEnabled = self.tableWidgetStandard.isSortingEnabled()
        self.tableWidgetStandard.setSortingEnabled(False)
        item = self.tableWidgetStandard.item(0, 0)
        item.setText(_translate("EnableTool", "初始状态"))
        item = self.tableWidgetStandard.item(0, 8)
        item.setText(_translate("EnableTool", "10000"))
        item = self.tableWidgetStandard.item(0, 9)
        item.setText(_translate("EnableTool", "10000"))
        item = self.tableWidgetStandard.item(0, 10)
        item.setText(_translate("EnableTool", "0"))
        item = self.tableWidgetStandard.item(0, 11)
        item.setText(_translate("EnableTool", "10000"))
        item = self.tableWidgetStandard.item(0, 12)
        item.setText(_translate("EnableTool", "100"))
        item = self.tableWidgetStandard.item(0, 13)
        item.setText(_translate("EnableTool", "1000000"))
        item = self.tableWidgetStandard.item(0, 14)
        item.setText(_translate("EnableTool", "1000000"))
        item = self.tableWidgetStandard.item(1, 0)
        item.setText(_translate("EnableTool", "计算后状态"))
        item = self.tableWidgetStandard.item(2, 0)
        item.setText(_translate("EnableTool", "初始化后状态"))
        self.tableWidgetStandard.setSortingEnabled(__sortingEnabled)

import ICON_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EnableTool = QtWidgets.QMainWindow()
    ui = Ui_EnableTool()
    ui.setupUi(EnableTool)
    EnableTool.show()
    sys.exit(app.exec_())

