# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\开发启蒙\可用工具开发\EnableTools\gongshi.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_gongshi(object):
    def setupUi(self, gongshi):
        gongshi.setObjectName("gongshi")
        gongshi.resize(1284, 549)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(21)
        gongshi.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/En/En.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        gongshi.setWindowIcon(icon)
        gongshi.setStyleSheet("")
        gongshi.setTabShape(QtWidgets.QTabWidget.Triangular)
        gongshi.setDockNestingEnabled(False)
        gongshi.setUnifiedTitleAndToolBarOnMac(False)
        self.gongshiWidget = QtWidgets.QWidget(gongshi)
        self.gongshiWidget.setObjectName("gongshiWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gongshiWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gstableWidget = QtWidgets.QTableWidget(self.gongshiWidget)
        self.gstableWidget.setEnabled(True)
        self.gstableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.gstableWidget.setStyleSheet("font: 12pt \"楷体\";")
        self.gstableWidget.setDragEnabled(True)
        self.gstableWidget.setObjectName("gstableWidget")
        self.gstableWidget.setColumnCount(3)
        self.gstableWidget.setRowCount(21)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(15, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(17, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(18, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(18, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(19, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(19, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(20, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gstableWidget.setItem(20, 2, item)
        self.gstableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.gstableWidget.horizontalHeader().setMinimumSectionSize(26)
        self.gstableWidget.verticalHeader().setVisible(False)
        self.gstableWidget.verticalHeader().setDefaultSectionSize(28)
        self.gstableWidget.verticalHeader().setMinimumSectionSize(25)
        self.verticalLayout.addWidget(self.gstableWidget)
        gongshi.setCentralWidget(self.gongshiWidget)

        self.retranslateUi(gongshi)
        QtCore.QMetaObject.connectSlotsByName(gongshi)

    def retranslateUi(self, gongshi):
        _translate = QtCore.QCoreApplication.translate
        gongshi.setWindowTitle(_translate("gongshi", "计算日志"))
        item = self.gstableWidget.verticalHeaderItem(0)
        item.setText(_translate("gongshi", "资产变化"))
        item = self.gstableWidget.verticalHeaderItem(1)
        item.setText(_translate("gongshi", "资金变化"))
        item = self.gstableWidget.verticalHeaderItem(2)
        item.setText(_translate("gongshi", "证券变化"))
        item = self.gstableWidget.verticalHeaderItem(3)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.verticalHeaderItem(4)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.verticalHeaderItem(5)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.verticalHeaderItem(6)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.verticalHeaderItem(7)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.verticalHeaderItem(8)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.verticalHeaderItem(9)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.verticalHeaderItem(10)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.verticalHeaderItem(11)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.verticalHeaderItem(12)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.verticalHeaderItem(13)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.verticalHeaderItem(14)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.verticalHeaderItem(15)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.verticalHeaderItem(16)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.verticalHeaderItem(17)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.verticalHeaderItem(18)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.verticalHeaderItem(19)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.verticalHeaderItem(20)
        item.setText(_translate("gongshi", "New Row"))
        item = self.gstableWidget.horizontalHeaderItem(0)
        item.setText(_translate("gongshi", "因子类别"))
        item = self.gstableWidget.horizontalHeaderItem(1)
        item.setText(_translate("gongshi", "因素"))
        item = self.gstableWidget.horizontalHeaderItem(2)
        item.setText(_translate("gongshi", "计算公式"))
        __sortingEnabled = self.gstableWidget.isSortingEnabled()
        self.gstableWidget.setSortingEnabled(False)
        item = self.gstableWidget.item(0, 0)
        item.setText(_translate("gongshi", "资产变化"))
        item = self.gstableWidget.item(0, 1)
        item.setText(_translate("gongshi", "现金资产"))
        item = self.gstableWidget.item(0, 2)
        item.setText(_translate("gongshi", "期初现金余额+当天业务处理资金变化部分＋手工调整部分\n"
""))
        item = self.gstableWidget.item(1, 1)
        item.setText(_translate("gongshi", "证券资产"))
        item = self.gstableWidget.item(1, 2)
        item.setText(_translate("gongshi", "最新价*持仓数量"))
        item = self.gstableWidget.item(2, 1)
        item.setText(_translate("gongshi", "应收"))
        item = self.gstableWidget.item(2, 2)
        item.setText(_translate("gongshi", "表示应收科目余额的合计"))
        item = self.gstableWidget.item(3, 1)
        item.setText(_translate("gongshi", "应付"))
        item = self.gstableWidget.item(3, 2)
        item.setText(_translate("gongshi", "表示应付科目余额的合计"))
        item = self.gstableWidget.item(4, 1)
        item.setText(_translate("gongshi", "总资产"))
        item = self.gstableWidget.item(4, 2)
        item.setText(_translate("gongshi", "当前资金余额+合计应收金额+股票资产+债券资产+基金资产+回购资产+权证资产+其他资产+期货盈亏+期权资产+应收证券资产+应付债券资产"))
        item = self.gstableWidget.item(5, 1)
        item.setText(_translate("gongshi", "净值"))
        item = self.gstableWidget.item(5, 2)
        item.setText(_translate("gongshi", "当前现金余额 - 合计应付 + 合计应收 + 股票资产 + 债券资产+ 基金资产 + 回购资产 + 权证资产 + 其它资产 +　期货盈亏＋应收证券资产－应付证券资产＋期权资产"))
        item = self.gstableWidget.item(6, 1)
        item.setText(_translate("gongshi", "产品份额"))
        item = self.gstableWidget.item(6, 2)
        item.setText(_translate("gongshi", "产品成立之初建立的份额"))
        item = self.gstableWidget.item(7, 1)
        item.setText(_translate("gongshi", "单位净值"))
        item = self.gstableWidget.item(7, 2)
        item.setText(_translate("gongshi", "产品净资产/产品份额"))
        item = self.gstableWidget.item(8, 0)
        item.setText(_translate("gongshi", "资金变化"))
        item = self.gstableWidget.item(8, 1)
        item.setText(_translate("gongshi", "交易费\n"
""))
        item = self.gstableWidget.item(8, 2)
        item.setText(_translate("gongshi", "成交金额*费率"))
        item = self.gstableWidget.item(9, 1)
        item.setText(_translate("gongshi", "当前现金余额\n"
""))
        item = self.gstableWidget.item(9, 2)
        item.setText(_translate("gongshi", "期初现金余额+当天业务处理资金变化部分＋手工调整部分"))
        item = self.gstableWidget.item(10, 1)
        item.setText(_translate("gongshi", "T+0可用金额"))
        item = self.gstableWidget.item(10, 2)
        item.setText(_translate("gongshi", " 当前金额-冻结金额+解冻金额+Min{T+1变化-T+1冻结金额-指令占用,0}"))
        item = self.gstableWidget.item(11, 1)
        item.setText(_translate("gongshi", "T+1可用金额"))
        item = self.gstableWidget.item(11, 2)
        item.setText(_translate("gongshi", " 当前金额-冻结金额+解冻金额+T+1变化-T+1冻结金额-指令占用"))
        item = self.gstableWidget.item(12, 1)
        item.setText(_translate("gongshi", "冻结金额\n"
""))
        item = self.gstableWidget.item(12, 2)
        item.setText(_translate("gongshi", "将要流还未流出的资金"))
        item = self.gstableWidget.item(13, 1)
        item.setText(_translate("gongshi", "解冻金额"))
        item = self.gstableWidget.item(13, 2)
        item.setText(_translate("gongshi", "将要进还未进的资金"))
        item = self.gstableWidget.item(14, 0)
        item.setText(_translate("gongshi", "证券变化"))
        item = self.gstableWidget.item(14, 1)
        item.setText(_translate("gongshi", "当前持仓数量\n"
""))
        item = self.gstableWidget.item(14, 2)
        item.setText(_translate("gongshi", "当前持仓数量"))
        item = self.gstableWidget.item(15, 1)
        item.setText(_translate("gongshi", "可用数量\n"
""))
        item = self.gstableWidget.item(15, 2)
        item.setText(_translate("gongshi", "当前数量-冻结数量+解冻数量+买抵扣数量+买锁定数量+min{T+1变化-T+1冻结数量,0}"))
        item = self.gstableWidget.item(16, 1)
        item.setText(_translate("gongshi", "冻结数量\n"
""))
        item = self.gstableWidget.item(16, 2)
        item.setText(_translate("gongshi", "将要流还未流出的持仓"))
        item = self.gstableWidget.item(17, 1)
        item.setText(_translate("gongshi", "解冻数量\n"
""))
        item = self.gstableWidget.item(17, 2)
        item.setText(_translate("gongshi", "将要进还未进的持仓"))
        item = self.gstableWidget.item(18, 1)
        item.setText(_translate("gongshi", "成本价\n"
""))
        item = self.gstableWidget.item(18, 2)
        item.setText(_translate("gongshi", "当前数量+卖出数量=0，成本价=0；当前数量+卖出数量<>0成本价=成本/（当前数量+卖出数量）"))
        item = self.gstableWidget.item(19, 1)
        item.setText(_translate("gongshi", "成本\n"
""))
        item = self.gstableWidget.item(19, 2)
        item.setText(_translate("gongshi", "当前数量+卖出数量=0，为0；当前数量+卖出数量<>0，=当前数量 *　成本价"))
        item = self.gstableWidget.item(20, 1)
        item.setText(_translate("gongshi", "含费用成本\n"
""))
        item = self.gstableWidget.item(20, 2)
        item.setText(_translate("gongshi", "结转过含费用的期初成本+买入金额+实际当日买入费用"))
        self.gstableWidget.setSortingEnabled(__sortingEnabled)

import ICON_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gongshi = QtWidgets.QMainWindow()
    ui = Ui_gongshi()
    ui.setupUi(gongshi)
    gongshi.show()
    sys.exit(app.exec_())

