# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\开发启蒙\可用工具开发\EnableTools\menu.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 618)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        self.menu_6.setObjectName("menu_6")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setText("")
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.action1_2 = QtWidgets.QAction(MainWindow)
        self.action1_2.setCheckable(False)
        self.action1_2.setEnabled(True)
        self.action1_2.setStatusTip("")
        self.action1_2.setWhatsThis("")
        self.action1_2.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.action1_2.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.action1_2.setPriority(QtWidgets.QAction.NormalPriority)
        self.action1_2.setObjectName("action1_2")
        self.action2_2 = QtWidgets.QAction(MainWindow)
        self.action2_2.setObjectName("action2_2")
        self.action1_3 = QtWidgets.QAction(MainWindow)
        self.action1_3.setObjectName("action1_3")
        self.action2_3 = QtWidgets.QAction(MainWindow)
        self.action2_3.setObjectName("action2_3")
        self.action3_2 = QtWidgets.QAction(MainWindow)
        self.action3_2.setObjectName("action3_2")
        self.actionaa = QtWidgets.QAction(MainWindow)
        self.actionaa.setObjectName("actionaa")
        self.MShareTrade = QtWidgets.QAction(MainWindow)
        self.MShareTrade.setObjectName("MShareTrade")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.action2_4 = QtWidgets.QAction(MainWindow)
        self.action2_4.setObjectName("action2_4")
        self.calcLog = QtWidgets.QAction(MainWindow)
        self.calcLog.setObjectName("calcLog")
        self.gongshi = QtWidgets.QAction(MainWindow)
        self.gongshi.setEnabled(True)
        self.gongshi.setObjectName("gongshi")
        self.menu_2.addAction(self.MShareTrade)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action1_2)
        self.menu_3.addAction(self.action2_2)
        self.menu_3.addAction(self.actionaa)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action1_3)
        self.menu_4.addAction(self.action2_3)
        self.menu_4.addAction(self.action3_2)
        self.menu_5.addAction(self.calcLog)
        self.menu_5.addAction(self.gongshi)
        self.menu_6.addAction(self.actionAbout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "简用"))
        self.label.setText(_translate("MainWindow", "欢迎使用简用-业务逻辑展示小工具"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "首页"))
        self.menu.setTitle(_translate("MainWindow", "首页"))
        self.menu_2.setTitle(_translate("MainWindow", "股票交易"))
        self.menu_3.setTitle(_translate("MainWindow", "债券交易"))
        self.menu_4.setTitle(_translate("MainWindow", "融资融券"))
        self.menu_5.setTitle(_translate("MainWindow", "日志显示"))
        self.menu_6.setTitle(_translate("MainWindow", "关于"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.action3.setText(_translate("MainWindow", "3"))
        self.action1_2.setText(_translate("MainWindow", "债券交易"))
        self.action2_2.setText(_translate("MainWindow", "债券质押"))
        self.action1_3.setText(_translate("MainWindow", "融资买入"))
        self.action2_3.setText(_translate("MainWindow", "融资卖出"))
        self.action3_2.setText(_translate("MainWindow", "买券还券"))
        self.actionaa.setText(_translate("MainWindow", "债券回购"))
        self.MShareTrade.setText(_translate("MainWindow", "股票买卖"))
        self.actionAbout.setText(_translate("MainWindow", "系统介绍"))
        self.action2_4.setText(_translate("MainWindow", "2、系统版本说明"))
        self.calcLog.setText(_translate("MainWindow", "计算日志"))
        self.gongshi.setText(_translate("MainWindow", "公式显示"))

import ICON_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

